# Generated by Django 3.2.5 on 2022-05-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proleague', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='duration',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='proleague.position'),
        ),
    ]
