# Generated by Django 3.2.5 on 2022-05-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proleague', '0003_auto_20220506_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['team_a__tournament', 'match_time']},
        ),
    ]
